- Makefile
uwc-docs : Updated Makefile with docs folder to reflect build to docs renaming.
> uwc-docs : Updated Makefile with docs folder to reflect build to docs renaming

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- source/conf.py
uwc-docs/workflows : Update branch main to develop for workflows-edit button feature
> uwc-docs/workflows : Update branch main to develop for workflows-edit button feature

- source/Pages/page_03.rst
Test commit with dummy changes to User guide to verify if changes made thru edit button trigger workflow.
> Test commit to verify if changes made thru edit button trigger workflow

- .github/workflows/push.yml
Added the GITHUB_TOKEN to push.yml workflow file
Signed-off-by: Vinod K B <vinod.k.b@intel.com>
> .github: Added the GITHUB_TOKEN to push.yml

- source/Pages/page_14.rst
> Test commit to check auto CI

- source/Pages/page_01.rst
> Test commit 2 CI check

- README.md
- source/Pages/page_01.rst
- source/Pages/page_14.rst
uwc-docs : Readme steps simplified
1. Readme steps simplified
2. Undo older test commits
> uwc-docs : Readme steps simplified

- source/Pages/page_15.rst
Test commit for verifying edit button on main branch
> Test commit for verifying edit button on main branch

- source/Pages/page_15.rst
> undo the test changes

- source/Pages/page_02.rst
Update bullets with number bullets
> Update bullets with number bullets

- source/Pages/page_02.rst
Correcting the formatting issues with RST
> Correcting the formatting issues with RST

- source/Pages/page_15.rst
Test commit - Updated Appendix
> Test commit - Updated Appendix

- source/Pages/page_02.rst
> Formatting-update

- source/Pages/page_02.rst
> formatting-lines2

- source/Pages/page_02.rst
> Correcting the formatting

- source/Pages/page_07.rst
1. Update KPI-app section in UG
> Update KPI-app section in UG

- source/Pages/page_02.rst
uwc-docs : UG-Release notes update
> UG-Release notes update

- source/Pages/page_02.rst
Added the git clone commands to rel-notes of UWC-v1.5.1
> uwc-docs : Added the git clone commands to rel-notes of UWC-v1.5.1

- source/Pages/page_02.rst
> uwc-docs : Indentation correction

- source/Pages/page_02.rst
> uwc-docs : indentation

- source/Pages/page_02.rst
> uwc-docs : Indentation fix

- source/Pages/page_04.rst
1. Update UG with note to change the use case
> uwc-docs : Update UG with note to change the use case

- source/Pages/page_04.rst
> uwc-docs : Indentation update in note

- source/Pages/page_06.rst
> Updated page 06 of UG

- source/Pages/page_09.rst
> Updated page 09 of UG

- source/Pages/page_02.rst
> Updated page 02 of UG

- source/Pages/page_04.rst
> Updated page 04 of UG

- source/Pages/page_06.rst
> Updated page 06

- source/Pages/page_02.rst
Renamed instance of UWC to Universal Wellpad Controller.
> Updated page_02.rst

- source/Pages/page_06.rst
Suggestion: The following terms 'master' and 'slave' need to be replaced with more inclusive words such as primary or main and secondary. If this does not impact any code or labels then we can change this term to be more inclusive.
Hi @nagdeepgk, Please confirm if we can proceed with this change.
> Reviewed and updated page_06.rst

- source/Pages/page_05.rst
@nagdeepgk @aditisa1 Please review and merge.
> Reviewed and updated page05.rst

- source/Pages/page_04.rst
Corrected bold formatting to fix the issue with content rendering for the procedure steps.
> Updated page_04
